import type { editor } from "monaco-editor";

export const nexusDarkTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "e2e8f0", background: "0f1423" },
    { token: "comment", foreground: "64748b", fontStyle: "italic" },
    { token: "keyword", foreground: "c084fc" },
    { token: "keyword.control", foreground: "c084fc" },
    { token: "keyword.operator", foreground: "c084fc" },
    { token: "storage", foreground: "c084fc" },
    { token: "storage.type", foreground: "c084fc" },
    { token: "type", foreground: "22d3ee" },
    { token: "type.identifier", foreground: "22d3ee" },
    { token: "string", foreground: "34d399" },
    { token: "string.escape", foreground: "5eead4" },
    { token: "number", foreground: "fbbf24" },
    { token: "constant", foreground: "fbbf24" },
    { token: "variable", foreground: "e2e8f0" },
    { token: "variable.predefined", foreground: "818cf8" },
    { token: "variable.parameter", foreground: "f0abfc" },
    { token: "function", foreground: "818cf8" },
    { token: "function.declaration", foreground: "818cf8" },
    { token: "operator", foreground: "94a3b8" },
    { token: "delimiter", foreground: "94a3b8" },
    { token: "delimiter.bracket", foreground: "94a3b8" },
    { token: "tag", foreground: "fb7185" },
    { token: "attribute.name", foreground: "fbbf24" },
    { token: "attribute.value", foreground: "34d399" },
    { token: "metatag", foreground: "94a3b8" },
    { token: "regexp", foreground: "fb7185" },
    { token: "annotation", foreground: "fbbf24" },
    { token: "decorator", foreground: "fbbf24" },
  ],
  colors: {
    "editor.background": "#0f1423",
    "editor.foreground": "#e2e8f0",
    "editor.lineHighlightBackground": "#1a213822",
    "editor.selectionBackground": "#6366f133",
    "editor.inactiveSelectionBackground": "#6366f11a",
    "editor.selectionHighlightBackground": "#6366f11a",
    "editor.findMatchBackground": "#fbbf2433",
    "editor.findMatchHighlightBackground": "#fbbf2422",
    "editorLineNumber.foreground": "#334155",
    "editorLineNumber.activeForeground": "#64748b",
    "editorCursor.foreground": "#6366f1",
    "editorWhitespace.foreground": "#1e293b",
    "editorIndentGuide.background": "#1e293b",
    "editorIndentGuide.activeBackground": "#334155",
    "editorBracketMatch.background": "#6366f122",
    "editorBracketMatch.border": "#6366f155",
    "editorGutter.background": "#0f1423",
    "editorOverviewRuler.border": "#1e293b",
    "editor.wordHighlightBackground": "#6366f11a",
    "editor.wordHighlightStrongBackground": "#6366f126",
    "editorSuggestWidget.background": "#151b2e",
    "editorSuggestWidget.border": "#1e293b",
    "editorSuggestWidget.foreground": "#e2e8f0",
    "editorSuggestWidget.highlightForeground": "#6366f1",
    "editorSuggestWidget.selectedBackground": "#252d4a",
    "editorHoverWidget.background": "#151b2e",
    "editorHoverWidget.border": "#1e293b",
    "editorWidget.background": "#151b2e",
    "editorWidget.border": "#1e293b",
    "peekViewEditor.background": "#0f1423",
    "peekViewResult.background": "#151b2e",
    "peekViewTitle.background": "#151b2e",
    "minimap.background": "#0a0e1a",
    "scrollbar.shadow": "#00000066",
    "scrollbarSlider.background": "#33415566",
    "scrollbarSlider.hoverBackground": "#47556988",
    "scrollbarSlider.activeBackground": "#475569aa",
  },
};
